import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { ChangePasswordSchema, TotpEnrollSchema, TotpDisableSchema, TotpVerifySchema, type SessionResponse } from '@aljeel/shared';
import { ShieldCheck, KeyRound, Monitor, CheckCircle2 } from 'lucide-react';
import { api, ApiError } from './api';
import { useSession } from './App';
import { useI18n } from './i18n';
import { Confirm, ErrorBox, FieldError, Loading, useToast } from './components';
export function Security({ required = false }: { required?: boolean }) {
  const { t } = useI18n();
  return <><div className="page-heading"><div><span className="eyebrow">{t('protected')}</span><h1>{t(required ? 'changeRequired' : 'security')}</h1><p className="muted">{t(required ? 'changeRequiredNote' : 'securityIntro')}</p></div></div><div className={required ? 'required-card card' : 'security-grid'}><PasswordForm/>{!required && <><TotpForm/><Sessions/></>}</div></>;
}
function PasswordForm() {
  const { t } = useI18n(); const client = useQueryClient(); const toast = useToast(); const [error, setError] = useState('');
  const { register, reset, handleSubmit, formState: { errors, isSubmitting } } = useForm<z.infer<typeof ChangePasswordSchema>>({ resolver: zodResolver(ChangePasswordSchema) });
  return <section className="card security-card"><div className="section-icon"><KeyRound size={23}/></div><h2>{t('changePassword')}</h2><p className="muted">{t('passwordHelp')}</p><form onSubmit={handleSubmit(async values => { setError(''); try { const session = await api<SessionResponse>('/auth/change-password', { method: 'POST', body: values }); client.setQueryData(['session'], session); await client.invalidateQueries({ queryKey: ['sessions'] }); reset(); toast(t('success')); } catch (error) { setError(error instanceof ApiError ? error.code : 'failed'); } })}><ErrorBox code={error}/><label>{t('currentPassword')}<input dir="ltr" type="password" autoComplete="current-password" {...register('currentPassword')}/><FieldError message={errors.currentPassword?.message}/></label><label>{t('newPassword')}<input dir="ltr" type="password" autoComplete="new-password" {...register('newPassword')}/><FieldError message={errors.newPassword?.message}/></label><button className="button primary" disabled={isSubmitting}>{t(isSubmitting ? 'saving' : 'changePassword')}</button></form></section>;
}
function TotpForm() {
  const { user } = useSession(); const { t } = useI18n(); const client = useQueryClient(); const toast = useToast(); const [error, setError] = useState(''); const [setup, setSetup] = useState<{ secret: string; uri: string } | null>(null);
  const enroll = useForm<z.infer<typeof TotpEnrollSchema>>({ resolver: zodResolver(TotpEnrollSchema) });
  const verify = useForm<z.infer<typeof TotpVerifySchema>>({ resolver: zodResolver(TotpVerifySchema) });
  const disable = useForm<z.infer<typeof TotpDisableSchema>>({ resolver: zodResolver(TotpDisableSchema) });
  async function refresh() { await client.invalidateQueries({ queryKey: ['session'] }); await client.invalidateQueries({ queryKey: ['sessions'] }); toast(t('success')); setSetup(null); enroll.reset(); verify.reset(); disable.reset(); }
  return <section className="card security-card"><div className="security-title"><div className="section-icon amber-soft"><ShieldCheck size={23}/></div><span className={`status-badge ${user.totpEnabled ? 'active' : 'inactive'}`}>{t(user.totpEnabled ? 'enabled' : 'notEnabled')}</span></div><h2>{t('twoFactor')}</h2><p className="muted">{t('totpNote')}</p><ErrorBox code={error}/>{user.totpEnabled ? <form onSubmit={disable.handleSubmit(async values => { setError(''); try { await api('/auth/totp/disable', { method: 'POST', body: values }); await refresh(); } catch (error) { setError(error instanceof ApiError ? error.code : 'failed'); } })}><label>{t('currentPassword')}<input type="password" dir="ltr" autoComplete="current-password" {...disable.register('password')}/><FieldError message={disable.formState.errors.password?.message}/></label><label>{t('code')}<input dir="ltr" inputMode="numeric" maxLength={6} autoComplete="one-time-code" {...disable.register('code')}/><FieldError message={disable.formState.errors.code?.message}/></label><button className="button secondary" disabled={disable.formState.isSubmitting}>{t('disableTotp')}</button></form> : setup ? <form onSubmit={verify.handleSubmit(async values => { setError(''); try { await api('/auth/totp/verify', { method: 'POST', body: values }); await refresh(); } catch (error) { setError(error instanceof ApiError ? error.code : 'failed'); } })}><p className="setup-note">{t('setupNote')}</p><label>{t('setupKey')}<input dir="ltr" className="setup-key" value={setup.secret} readOnly onFocus={event => event.target.select()}/></label><label>{t('code')}<input dir="ltr" inputMode="numeric" maxLength={6} autoComplete="one-time-code" {...verify.register('code')}/><FieldError message={verify.formState.errors.code?.message}/></label><button className="button primary" disabled={verify.formState.isSubmitting}>{t('verify')}</button><button type="button" className="button subtle" onClick={() => setSetup(null)}>{t('cancel')}</button></form> : <form onSubmit={enroll.handleSubmit(async values => { setError(''); try { setSetup(await api('/auth/totp/enroll', { method: 'POST', body: values })); enroll.reset(); } catch (error) { setError(error instanceof ApiError ? error.code : 'failed'); } })}><label>{t('currentPassword')}<input type="password" dir="ltr" autoComplete="current-password" {...enroll.register('password')}/><FieldError message={enroll.formState.errors.password?.message}/></label><button className="button secondary" disabled={enroll.formState.isSubmitting}>{t('enroll')}</button></form>}</section>;
}
function Sessions() {
  const { t, date } = useI18n(); const toast = useToast(); const client = useQueryClient();
  const query = useQuery({ queryKey: ['sessions'], queryFn: () => api<{ items: { id: string; createdAt: string; expiresAt: string; userAgent: string; current: boolean }[] }>('/auth/sessions') });
  return <section className="card security-card sessions-card"><div className="section-icon soft"><Monitor size={23}/></div><h2>{t('sessions')}</h2><p className="muted">{t('sessionsNote')}</p>{query.isPending ? <Loading/> : query.isError ? <ErrorBox code={query.error instanceof ApiError ? query.error.code : 'failed'}/> : query.data.items.map(session => <div className="session-row" key={session.id}><div><strong>{session.current && <><CheckCircle2 size={16}/>{t('thisSession')} · </>}{session.userAgent || t('unknownDevice')}</strong><small>{date(session.createdAt)} · {t('expires')} {date(session.expiresAt)}</small></div><Confirm title={t('revoke')} description={t('revokeNote')} onConfirm={async () => { try { await api(`/auth/sessions/${session.id}`, { method: 'DELETE' }); await client.invalidateQueries({ queryKey: ['sessions'] }); if (session.current) await client.invalidateQueries({ queryKey: ['session'] }); toast(t('success')); } catch (error) { toast(t(error instanceof ApiError ? error.code : 'failed'), true); } }}>{t('revoke')}</Confirm></div>)}</section>;
}
