import { useEffect, useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useReactTable, getCoreRowModel, flexRender, type ColumnDef } from '@tanstack/react-table';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { StaffCreateSchema, PasswordSchema, ResetPasswordSchema, roles, type PublicUser } from '@aljeel/shared';
import { Plus, Search, Pencil, KeyRound, ShieldOff, UserRoundX } from 'lucide-react';
import { api, ApiError } from './api';
import { useI18n } from './i18n';
import { useSession } from './App';
import { Confirm, ErrorBox, FieldError, Loading, Modal, useToast } from './components';
type StaffResult = { items: PublicUser[]; total: number; page: number; pageSize: number };
export function Staff() {
  const { t, date } = useI18n(); const { user: current } = useSession(); const toast = useToast(); const client = useQueryClient();
  const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [debounced, setDebounced] = useState(''); const [role, setRole] = useState(''); const [editor, setEditor] = useState<PublicUser | 'new' | null>(null); const [reset, setReset] = useState<PublicUser | null>(null);
  useEffect(() => { const timer = setTimeout(() => { setDebounced(search); setPage(1); }, 300); return () => clearTimeout(timer); }, [search]);
  const query = useQuery({ queryKey: ['users', page, debounced, role], queryFn: () => api<StaffResult>(`/users?${new URLSearchParams({ page: String(page), pageSize: '20', search: debounced, ...(role ? { role } : {}) })}`) });
  const mutate = async (path: string, method: string, body?: unknown) => { try { await api(path, { method, body }); await client.invalidateQueries({ queryKey: ['users'] }); await client.invalidateQueries({ queryKey: ['audit'] }); if (path.includes(current.id)) await client.invalidateQueries({ queryKey: ['session'] }); toast(t('success')); } catch (error) { toast(t(error instanceof ApiError ? error.code : 'failed'), true); } };
  const columns = useMemo<ColumnDef<PublicUser>[]>(() => [
    { header: t('name'), accessorKey: 'name', cell: ({ row }) => <div className="person-cell"><span className="avatar small">{row.original.name.charAt(0)}</span><div><strong>{row.original.name}</strong><span dir="ltr">{row.original.email}</span></div></div> },
    { header: t('role'), accessorKey: 'role', cell: ({ row }) => <span className={`role-badge ${row.original.role}`}>{t(row.original.role)}</span> },
    { header: t('status'), accessorKey: 'isActive', cell: ({ row }) => <div><span className={`status-badge ${row.original.isActive ? 'active' : 'inactive'}`}>{t(row.original.isActive ? 'active' : 'inactive')}</span>{row.original.mustChangePassword && <small className="muted block">{t('mustChange')}</small>}</div> },
    { header: t('lastLogin'), accessorKey: 'lastLoginAt', cell: ({ row }) => <span className="muted">{date(row.original.lastLoginAt)}</span> },
    { id: 'actions', header: t('actions'), cell: ({ row }) => <div className="row-actions"><button className="icon-button" title={t('edit')} aria-label={`${t('edit')} ${row.original.name}`} onClick={() => setEditor(row.original)}><Pencil size={16}/></button><button className="icon-button" title={t('resetPassword')} aria-label={`${t('resetPassword')} ${row.original.name}`} onClick={() => setReset(row.original)}><KeyRound size={16}/></button><Confirm title={t('resetTotp')} description={t('resetTotpNote')} onConfirm={() => mutate(`/users/${row.original.id}/reset-totp`, 'POST', {})}><ShieldOff size={16}/><span className="sr-only">{t('resetTotp')}</span></Confirm>{row.original.isActive ? <Confirm title={t('deactivate')} description={t('deactivateNote')} onConfirm={() => mutate(`/users/${row.original.id}`, 'DELETE')}><UserRoundX size={16}/><span className="sr-only">{t('deactivate')}</span></Confirm> : <button className="button subtle" onClick={() => mutate(`/users/${row.original.id}`, 'PATCH', { isActive: true })}>{t('reactivate')}</button>}</div> },
  ], [t, date, current.id]);
  const table = useReactTable({ data: query.data?.items ?? [], columns, getCoreRowModel: getCoreRowModel(), manualPagination: true, rowCount: query.data?.total ?? 0 });
  return <><div className="page-heading"><div><span className="eyebrow">{t('currentAccess')}</span><h1>{t('staff')}</h1><p className="muted">{t('staffDescription')}</p></div><button className="button primary" onClick={() => setEditor('new')}><Plus size={18}/>{t('addStaff')}</button></div><section className="card table-card"><div className="table-toolbar"><div className="search-field"><Search size={18}/><input aria-label={t('searchStaff')} placeholder={t('searchStaff')} value={search} onChange={event => setSearch(event.target.value)}/></div><select aria-label={t('role')} value={role} onChange={event => { setRole(event.target.value); setPage(1); }}><option value="">{t('allRoles')}</option>{roles.map(role => <option key={role} value={role}>{t(role)}</option>)}</select></div>{query.isPending ? <Loading/> : query.isError ? <ErrorBox code={query.error instanceof ApiError ? query.error.code : 'failed'}/> : query.data.items.length === 0 ? <div className="table-empty">{t('staffEmpty')}</div> : <div className="table-scroll"><table><thead>{table.getHeaderGroups().map(group => <tr key={group.id}>{group.headers.map(header => <th key={header.id}>{flexRender(header.column.columnDef.header, header.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(row => <tr key={row.id}>{row.getVisibleCells().map(cell => <td key={cell.id} data-label={typeof cell.column.columnDef.header === 'string' ? cell.column.columnDef.header : ''}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>)}</tbody></table></div>}<div className="pagination"><span>{query.data?.total ?? '—'} {t('people')}</span><div><button className="button secondary" disabled={page <= 1} onClick={() => setPage(page - 1)}>{t('previous')}</button><span>{t('page')} {page}</span><button className="button secondary" disabled={!query.data || page * 20 >= query.data.total} onClick={() => setPage(page + 1)}>{t('next')}</button></div></div></section><Modal open={editor !== null} onOpenChange={open => { if (!open) setEditor(null); }} title={t(editor === 'new' ? 'addStaff' : 'editStaff')}>{editor && <StaffEditor key={editor === 'new' ? 'new' : editor.id} user={editor === 'new' ? null : editor} onSaved={() => setEditor(null)}/>}</Modal><Modal open={reset !== null} onOpenChange={open => { if (!open) setReset(null); }} title={t('resetPassword')} description={t('passwordHelp')}>{reset && <PasswordReset user={reset} onSaved={() => setReset(null)}/>}</Modal></>;
}
function StaffEditor({ user, onSaved }: { user: PublicUser | null; onSaved: () => void }) {
  const { t } = useI18n(); const client = useQueryClient(); const toast = useToast(); const [error, setError] = useState('');
  const schema = StaffCreateSchema.extend({ password: PasswordSchema.or(z.literal('')).optional() }).refine(values => user || Boolean(values.password), { path: ['password'], message: 'required' });
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<z.infer<typeof schema>>({ resolver: zodResolver(schema), defaultValues: user ? { email: user.email, name: user.name, role: user.role } : { role: 'viewer' } });
  return <form onSubmit={handleSubmit(async values => { setError(''); try { const body = user ? { email: values.email, name: values.name, role: values.role } : values; await api(user ? `/users/${user.id}` : '/users', { method: user ? 'PATCH' : 'POST', body }); await client.invalidateQueries({ queryKey: ['users'] }); await client.invalidateQueries({ queryKey: ['session'] }); toast(t('success')); onSaved(); } catch (error) { setError(error instanceof ApiError ? error.code : 'failed'); } })}><ErrorBox code={error}/><label>{t('name')}<input autoComplete="name" {...register('name')}/><FieldError message={errors.name?.message}/></label><label>{t('email')}<input type="email" dir="ltr" autoComplete="email" {...register('email')}/><FieldError message={errors.email?.message}/></label><label>{t('role')}<select {...register('role')}>{roles.map(role => <option key={role} value={role}>{t(role)}</option>)}</select></label>{!user && <label>{t('temporaryPassword')}<input type="password" dir="ltr" autoComplete="new-password" {...register('password')}/><FieldError message={errors.password?.message}/><small className="muted">{t('passwordHelp')}</small></label>}<div className="dialog-actions"><button type="button" className="button secondary" onClick={onSaved}>{t('cancel')}</button><button className="button primary" disabled={isSubmitting}>{t(isSubmitting ? 'saving' : 'save')}</button></div></form>;
}
function PasswordReset({ user, onSaved }: { user: PublicUser; onSaved: () => void }) {
  const { t } = useI18n(); const client = useQueryClient(); const [error, setError] = useState(''); const toast = useToast();
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<z.infer<typeof ResetPasswordSchema>>({ resolver: zodResolver(ResetPasswordSchema) });
  return <form onSubmit={handleSubmit(async values => { try { await api(`/users/${user.id}/reset-password`, { method: 'POST', body: values }); await client.invalidateQueries({ queryKey: ['users'] }); await client.invalidateQueries({ queryKey: ['session'] }); toast(t('success')); onSaved(); } catch (error) { setError(error instanceof ApiError ? error.code : 'failed'); } })}><ErrorBox code={error}/><label>{t('temporaryPassword')}<input type="password" dir="ltr" autoComplete="new-password" {...register('password')}/><FieldError message={errors.password?.message}/></label><button className="button primary" disabled={isSubmitting}>{t(isSubmitting ? 'saving' : 'save')}</button></form>;
}
