import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {useLanguage} from '@/i18n/LanguageContext';
import {shopApi,commerceCopy,orderLabels,errorText,type Order} from '@/data/commerce';
import '@/commerce.css';
export default function OrderPage(){
  const {id}=useParams(),{language}=useLanguage(),t=commerceCopy[language],[data,setData]=useState<{order:Order;whatsapp:string|null}|null>(null),[error,setError]=useState('');
  useEffect(()=>{shopApi<{order:Order;whatsapp:string|null}>('/orders/'+id).then(setData).catch(e=>setError(errorText(e.message,language)));},[id,language]);
  const order=data?.order;
  const message=order?[t.follow,order.number,...order.items.map(item=>item.title[language]+' · '+item.sku+' × '+item.quantity+(item.unitId?' · '+t.unit+' '+item.unitId.slice(-6):'')),t.subtotal+': '+(order.currency==='USD'?'$'+order.subtotalUsd:order.subtotalYer+' YER'),...(order.hasUnpriced?[t.unknown]:[]),order.fulfillment.method==='delivery'?t.delivery+' — '+order.fulfillment.address:t.pickup,...(order.fulfillment.method==='delivery'?[t.deliveryFee]:[]),t.noReservation].join('\n'):'';
  return <main id="main-content" className="store-shell" dir={language==='ar'?'rtl':'ltr'}><Link to={'/'+language+'/account'}>{t.orders}</Link><h1>{t.saved}</h1>{error&&<p role="alert" className="store-error">{error}</p>}{!order?<p>{t.loading}</p>:<><div className="store-panel"><h2 dir="ltr"><strong>{order.number}</strong></h2><p>{orderLabels[language][order.status as keyof typeof orderLabels.ar]}</p>{order.items.map((item,i)=><div className="store-cart-line" key={i}><div><strong>{item.title[language]}</strong><small dir="ltr">{item.sku} × {item.quantity}</small></div><strong>{item.linePriceUsd?'$'+item.linePriceUsd:item.priceIncluded?t.included:t.unknown}</strong></div>)}<p>{t.subtotal}: <strong dir="ltr">{order.currency==='USD'?'$'+order.subtotalUsd:order.subtotalYer+' YER'}</strong></p>{order.hasUnpriced&&<p>{t.unknown}</p>}<p>{order.fulfillment.method==='delivery'?t.delivery+' · '+order.fulfillment.address:t.pickup}</p>{order.fulfillment.method==='delivery'&&<p>{t.deliveryFee}</p>}<p className="store-notice">{t.noReservation}</p></div>{data?.whatsapp&&order.status!=='cancelled'?<><a className="store-button" href={'https://wa.me/'+data.whatsapp+'?text='+encodeURIComponent(message)} target="_blank" rel="noopener noreferrer">{t.follow}</a><p className="store-notice">{t.notSent}</p></>:<p>{t.noWhatsapp}</p>}{['new','review'].includes(order.status)&&<button className="store-button secondary" onClick={async()=>{try{await shopApi('/orders/'+id+'/cancel','POST',{});setData(data?{...data,order:{...order,status:'cancelled'}}:null);}catch(e){setError(errorText(e instanceof Error?e.message:'',language));}}}>{t.cancel}</button>}</>}</main>;
}

