import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import * as Dialog from '@radix-ui/react-dialog';
import {X} from 'lucide-react';
import {useLanguage} from '@/i18n/LanguageContext';
import {shopApi,addCart,commerceCopy,errorText,type Localized,type Offer} from '@/data/commerce';
import '@/commerce.css';
type Package={id:string;title:Localized;description:Localized;priceUsd:string|null;available:boolean;items:{variantId:string;title:Localized;sku:string;inventoryMode:string;quantity:number;offers:Offer[]}[]};
export default function PackagesPage(){
  const {language}=useLanguage(),t=commerceCopy[language],[items,setItems]=useState<Package[]|null>(null),[selected,setSelected]=useState<Package|null>(null),[units,setUnits]=useState<string[]>([]),[error,setError]=useState(''),[added,setAdded]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{shopApi<{items:Package[]}>('/packages').then(r=>setItems(r.items)).catch(e=>setError(errorText(e.message,language)));},[language]);
  async function add(p:Package,unitIds:string[]=[]){setBusy(true);setError('');try{await addCart({packageId:p.id,quantity:1,...(unitIds.length?{unitIds}:{})});setAdded(p.id);setSelected(null);}catch(e){setError(errorText(e instanceof Error?e.message:'',language));}finally{setBusy(false);}}
  return <main className="store-shell" id="main-content" dir={language==='ar'?'rtl':'ltr'}><div className="store-actions"><Link to={'/'+language+'/shop'}>{t.continue}</Link><Link to={'/'+language+'/cart'}>{t.cart}</Link></div><h1>{t.packages}</h1>{error&&<p role="alert" className="store-error">{error}</p>}{items===null?<p>{t.loading}</p>:!items.length?<div className="store-empty">{t.empty}</div>:<div className="store-grid">{items.map(p=><article className="store-card" key={p.id}><div className="store-card-body"><h2>{p.title[language]}</h2><p>{p.description[language]}</p><ul>{p.items.map(i=><li key={i.variantId}>{i.title[language]} × {i.quantity}</li>)}</ul><div className="store-price"><strong>{p.priceUsd?'$'+p.priceUsd:t.ask}</strong></div><button className="store-button" disabled={!p.available||busy} onClick={()=>{if(p.items.some(i=>i.inventoryMode==='serialized')){setSelected(p);setUnits([]);}else void add(p);}}>{added===p.id?t.added:p.available?t.add:t.unavailable}</button></div></article>)}</div>}<Dialog.Root open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><Dialog.Portal><Dialog.Overlay className="store-overlay"/><Dialog.Content className="store-dialog" dir={language==='ar'?'rtl':'ltr'}><Dialog.Title>{t.chooseUnit}</Dialog.Title><Dialog.Description>{selected?.title[language]}</Dialog.Description><Dialog.Close className="store-close" aria-label={t.close}><X/></Dialog.Close>{selected?.items.filter(i=>i.inventoryMode==='serialized').map(i=><fieldset key={i.variantId}><legend>{i.title[language]} × {i.quantity}</legend>{i.offers.filter(o=>o.available&&o.unitId).map(o=><label className="offer-row" key={o.unitId}><input type="checkbox" checked={units.includes(o.unitId!)} onChange={e=>setUnits(e.target.checked?[...units,o.unitId!]:units.filter(id=>id!==o.unitId))}/><span>{t.unit} {o.unitId?.slice(-6)} · {o.condition} · {o.batteryHealthPct!==null?o.batteryHealthPct+'%':''}{o.defects?.map((d,i)=><small key={i}>{d[language]}</small>)}</span></label>)}</fieldset>)}<button className="store-button" disabled={busy||!selected?.items.filter(i=>i.inventoryMode==='serialized').every(i=>i.offers.filter(o=>o.unitId&&units.includes(o.unitId)).length===i.quantity)} onClick={()=>{if(selected)void add(selected,units);}}>{t.add}</button></Dialog.Content></Dialog.Portal></Dialog.Root></main>;
}

