import fs from 'node:fs';
import path from 'node:path';
import { home } from '../src/data/home';
import products from '../src/data/products.json';
import bundles from '../src/data/bundles.json';
import faq from '../src/data/faq.json';
import warranty from '../src/data/warranty.json';
const escape = (s: unknown) => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function staticHome() {
  const featured = products.find(p=>p.id===home.featuredId)!;
  const content = (language:'ar'|'en') => `<main class="static-home" lang="${language}" dir="${language==='ar'?'rtl':'ltr'}"><nav><a href="/${language}/shop">${home.shop[language]}</a> · <a href="/${language}/warranty">${home.warrantyLink[language]}</a></nav><h1>${home.title[language]}</h1><p>${home.intro[language]}</p><p>${home.demo[language]}</p>${home.chapters.slice(1).map(c=>`<section><h2>${c.title[language]}</h2><p>${c.body[language]}</p></section>`).join('')}<dl><dt>${home.specLabels[0][language]}</dt><dd>${escape(featured.specs.cpu)}</dd><dt>${home.specLabels[1][language]}</dt><dd>${featured.specs.ramGB} GB</dd><dt>${home.specLabels[2][language]}</dt><dd>${featured.specs.storageGB} GB</dd><dt>${home.specLabels[3][language]}</dt><dd>${home.batteryUnknown[language]}</dd></dl><p>${home.compatibilityUnknown[language]}</p><h2>${home.setupsTitle[language]}</h2>${bundles.map(b=>`<section><h3>${b.title[language]}</h3><p>${b.tiers[0].summary[language]}</p><ul>${b.tiers[0].items.map(id=>{const p=products.find(p=>p.id===id)!;return `<li><a href="/${language}/shop/${p.category}/${p.slug}">${escape(p.title[language])}</a></li>`}).join('')}</ul></section>`).join('')}<h2>${home.latest[language]}</h2><div class="static-products">${products.map(p=>`<article><img src="${p.images[0]}" width="480" height="320" loading="lazy" alt="${escape(p.title[language])}"/><h3><a href="/${language}/shop/${p.category}/${p.slug}">${escape(p.title[language])}</a></h3><p>${escape(p.summary[language])}</p><p>${language==='ar'?'اسأل عن السعر':'Ask for price'}</p></article>`).join('')}</div><h2>${home.inspectionTitle[language]}</h2><ul>${warranty.inspectionChecklist.map(c=>`<li>${escape(c.title[language])}</li>`).join('')}</ul><h2>${home.businessTitle[language]}</h2><ol>${home.steps.map(s=>`<li>${s[language]}</li>`).join('')}</ol><h2>${home.faqTitle[language]}</h2>${faq.slice(0,5).map(q=>`<details><summary>${escape(q.question[language])}</summary><p>${escape(q.answer[language])}</p></details>`).join('')}<h2>${home.briefTitle[language]}</h2><p>${home.noWhatsapp[language]}</p></main>`;
  const style='<style>.static-home{padding:35px;max-width:1200px;margin:auto;font:18px/1.9 LinaRound,sans-serif}.static-home section{margin-block:50px}.static-home h1{font-size:48px}.static-home h2{margin-block:25px}.static-home a{text-decoration:underline;color:var(--brand-text)}.static-products{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:25px}.static-products img{width:100%;height:auto;object-fit:contain;background:white}.static-home[lang=en]{display:none}html[lang=en] .static-home[lang=ar]{display:none}html[lang=en] .static-home[lang=en]{display:block}</style>';
  const file=path.resolve('dist/index.html');
  const html=fs.readFileSync(file,'utf8');
  fs.writeFileSync(file,html.replace(/<noscript>[\s\S]*?<\/noscript>/,`<noscript>${style}${content('ar')}${content('en')}</noscript>`));
}
