import {beforeAll,afterAll,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import mariadb,{type Connection} from 'mariadb';
import type {FastifyInstance,LightMyRequestResponse} from 'fastify';
import {type PrismaClient} from '@prisma/client';
import {buildApp} from '../src/app.js';
import {ConfigSchema} from '../src/config.js';
import {createDb} from '../src/db.js';
import {hashPassword,hashToken,randomToken} from '../src/security.js';
import {cartPreview,type SnapshotItem} from '../src/commerce-cart.js';
import {can} from '@aljeel/shared';
const url=new URL(process.env.TEST_DATABASE_URL??'mysql://missing@127.0.0.1:3306/missing');
if(!['127.0.0.1','localhost'].includes(url.hostname)||!process.env.TEST_DATABASE_URL)throw new Error('Local TEST_DATABASE_URL required');
const namespace='commerce_test_'+randomUUID().replaceAll('-',''),config=ConfigSchema.parse({NODE_ENV:'test',DATABASE_URL:url.toString(),SESSION_SECRET:randomToken(),TOTP_ENCRYPTION_KEY:'a'.repeat(64),ALLOWED_ORIGINS:'http://localhost:5174',LOG_LEVEL:'silent'});
let app:FastifyInstance,db:PrismaClient,sql:Connection,passwordHash:string;
type Browser={cookies:Map<string,string>;csrf:string;call:(path:string,method?:string,body?:unknown)=>Promise<LightMyRequestResponse>};
function browser(prefix='/api/shop'):Browser{const client:Browser={cookies:new Map(),csrf:'',async call(path,method='GET',body){const r=await app.inject({url:prefix+path,method:method as 'GET'|'POST'|'PATCH'|'DELETE',headers:{origin:'http://localhost:5174',cookie:[...client.cookies].map(([k,v])=>k+'='+v).join('; '),'x-csrf-token':client.csrf,...(body!==undefined?{'content-type':'application/json'}:{})},...(body!==undefined?{payload:JSON.stringify(body)}: {})});for(const c of r.cookies){if(c.value)client.cookies.set(c.name,c.value);else client.cookies.delete(c.name);}if(r.headers['content-type']?.includes('json')&&r.json().csrfToken)client.csrf=r.json().csrfToken;return r;}};return client;}
async function staff(role:'owner'|'sales'|'editor'='owner'){
  const user=await db.user.create({data:{email:randomUUID()+'@example.test',name:'Test staff',passwordHash,role,mustChangePassword:false}}),client=browser('/api/admin');await client.call('/auth/csrf');const raw=randomToken();await db.session.create({data:{id:hashToken(raw),userId:user.id,expiresAt:new Date(Date.now()+3600000),userAgent:'test',ipHash:'a'.repeat(64)}});client.cookies.set('aljeel_session',raw);return client;
}
async function account(){const c=await db.customerAccount.create({data:{name:'Isolated customer',phone:'+967'+String(Date.now()).slice(-7)+Math.floor(Math.random()*10000).toString().padStart(4,'0'),passwordHash}}),client=browser();await client.call('/csrf');const raw=randomToken();await db.customerSession.create({data:{id:hashToken(raw),customerId:c.id,expiresAt:new Date(Date.now()+3600000)}});client.cookies.set('store_session',raw);return {c,client};}
async function fixture(mode='quantity',quantity=5,price:string|null='100'){
  const id=randomUUID(),cat='cat-'+id,brand=await db.brand.create({data:{id:'brand-'+id,slug:'brand-'+id,name:'Isolated brand',published:true,description:{}}});
  await db.productType.create({data:{id:'type-'+id,title:{ar:'قالب اختبار',en:'Test template'},fields:[{key:'ramGB',title:{ar:'الذاكرة',en:'Memory'},valueType:'number',unit:'GB',options:[],required:true,filterable:true,card:true,sort:0}]}});
  await db.catalogCategory.create({data:{slug:cat,title:{ar:'فئة اختبار',en:'Test category'},description:{},productTypeId:'type-'+id}});
  const p=await db.product.create({data:{id,slug:'product-'+id,category:cat,brandId:brand.id,model:id,title:{ar:'اختبار '+id,en:'Test '+id},summary:{ar:'اختبار',en:'Test'},condition:'A',status:'published',specs:{},inspection:{passed:true},specSources:[],bestFor:[],tags:[],publishedAt:new Date()}});
  const v=await db.productVariant.create({data:{id:'variant-'+id,sku:'sku-'+id,productId:id,optionKey:'first',options:{ramGB:8},specs:{},images:[],priceUsd:price,condition:'A',inventoryMode:mode,quantity,inventoryReviewed:true}});
  const unit=mode==='serialized'?await db.inventoryUnit.create({data:{variantId:v.id,serialNumber:'private-'+id,condition:'B',batteryHealthPct:85,inspection:{passed:true},defects:[],images:[]}}):null;
  return {p,v,unit,cat,brand,id};
}
async function placed(customer:Awaited<ReturnType<typeof account>>,line:unknown){
  expect((await customer.client.call('/cart','POST',{items:[line]})).statusCode).toBe(200);
  const preview=(await customer.client.call('/cart')).json(),key=randomUUID(),r=await customer.client.call('/orders','POST',{previewToken:preview.previewToken,idempotencyKey:key,currency:'USD',fulfillment:{method:'pickup',address:'',notes:''}});
  expect(r.statusCode).toBe(201);return {order:r.json(),key,preview};
}
async function ready(admin:Browser,order:{id:string;updatedAt:string}){let current=order;for(const status of ['review','confirmed','preparing','ready_pickup']){const r=await admin.call('/commerce/orders/'+order.id+'/status','POST',{status,revision:current.updatedAt});expect(r.statusCode).toBe(200);current=r.json();}return current;}
beforeAll(async()=>{
  sql=await mariadb.createConnection({host:url.hostname,port:Number(url.port||3306),user:decodeURIComponent(url.username),password:decodeURIComponent(url.password),allowPublicKeyRetrieval:true});
  await sql.query('CREATE DATABASE '+namespace+' CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');await sql.query('USE '+namespace);
  for(const folder of ['202610030001_mysql','202610030002_checks','202610030003_commerce','202610030004_commerce_integrity','202610030005_commerce_checks']){const text=await readFile(new URL('../prisma/mysql-migrations/'+folder+'/migration.sql',import.meta.url),'utf8');for(const stmt of text.split(';').map(s=>s.trim()).filter(Boolean)){for(let attempt=0;;attempt++){try{await sql.query(stmt);break;}catch(error){if((error as {code:string}).code!=='ER_ERROR_ON_RENAME'||attempt>=5)throw error;await new Promise(resolve=>setTimeout(resolve,500));}}}}
  url.pathname='/'+namespace;db=createDb(url.toString());passwordHash=await hashPassword(randomToken());app=await buildApp(config,db,{disableRateLimits:true});await app.ready();
},60000);
afterAll(async()=>{if(app)await app.close();if(db)await db.$disconnect();if(sql){await sql.query('DROP DATABASE IF EXISTS '+namespace);await sql.end();}});
it('filters must match one SKU, OR within selections, and count alternatives with self-exclusion',async()=>{
  const {p,v,id,cat}=await fixture();await db.productVariant.create({data:{id:randomUUID(),sku:'second-'+id,productId:p.id,optionKey:'second',options:{ramGB:16},specs:{},images:[],priceUsd:'200',condition:'A',quantity:5,inventoryReviewed:true}});
  const client=browser(),base='/catalog?category='+cat+'&';
  let r=await client.call(base+'spec_ramGB=16&max=150');expect(r.json().total).toBe(0);
  r=await client.call(base+'spec_ramGB=8');expect(r.json().total).toBe(1);expect(r.json().facets.specs[0].values.map((f:{value:string})=>f.value)).toEqual(['8','16']);
  r=await client.call(base+'spec_ramGB=8&spec_ramGB=16');expect(r.json().items[0].offers).toHaveLength(2);expect(r.json().items[0].offers.map((o:{variantId:string})=>o.variantId)).toContain(v.id);
});
it('includes descendants and rejects circular categories',async()=>{const {cat}=await fixture(),root='root-'+randomUUID();await db.catalogCategory.create({data:{slug:root,title:{ar:'جذر',en:'Root'},description:{}}});await db.catalogCategory.update({where:{slug:cat},data:{parentSlug:root}});expect((await browser().call('/catalog?category='+root)).json().total).toBe(1);const admin=await staff();const r=await admin.call('/commerce/categories','POST',{slug:root,title:{ar:'جذر',en:'Root'},description:{ar:'وصف',en:'Description'},parentSlug:cat,productTypeId:null,imageId:null,status:'published',sort:0});expect(r.statusCode).toBe(400);expect(r.json().error.code).toBe('category_cycle');});
it('preserves null prices and uses exact decimal conversion; rate changes invalidate preview',async()=>{const {v}=await fixture('quantity',5,null);await db.pricingConfig.upsert({where:{id:1},create:{usdToYer:'250.125'},update:{usdToYer:'250.125'}});const preview=await cartPreview(db,[{variantId:v.id,quantity:2}]);expect(preview.hasUnpriced).toBe(true);expect(preview.items[0].unitPriceUsd).toBeNull();expect(preview.subtotalUsd).toBe('0.00');await db.productVariant.update({where:{id:v.id},data:{priceUsd:'0.10'}});const second=await cartPreview(db,[{variantId:v.id,quantity:3}]);expect(second.subtotalUsd).toBe('0.30');expect(second.subtotalYer).toBe('75.04');expect(second.previewToken).not.toBe(preview.previewToken);});
it('requires customer login and CSRF; staff session cannot authenticate a customer',async()=>{const b=browser();expect((await b.call('/register','POST',{name:'Test',phone:'+967712345678',password:randomToken()})).statusCode).toBe(403);await b.call('/csrf');expect((await b.call('/orders','POST',{})).statusCode).toBe(401);const admin=await staff();const raw=admin.cookies.get('aljeel_session')!;b.cookies.set('store_session',raw);expect((await b.call('/account')).json().customer).toBeNull();});
it('merges visitor cart after registration and hashes sessions, with no automatic CRM linking',async()=>{const {v}=await fixture(),b=browser();await b.call('/csrf');await b.call('/cart');expect((await b.call('/cart','POST',{items:[{variantId:v.id,quantity:2}]})).statusCode).toBe(200);const phone='+967'+String(Date.now()).slice(-11);await db.customer.create({data:{phone,name:'Historic CRM',tags:[],firstSource:'manual'}});const r=await b.call('/register','POST',{name:'New account',phone,password:randomToken()});expect(r.statusCode).toBe(200);expect(r.json().customer.phoneVerified).toBe(false);expect((await b.call('/cart')).json().items[0].quantity).toBe(2);const raw=b.cookies.get('store_session')!;expect(await db.customerSession.findUnique({where:{id:raw}})).toBeNull();expect(await db.customerSession.findUnique({where:{id:hashToken(raw)}})).not.toBeNull();});
it('creates idempotent orders without reservations and protects ownership and cancellation',async()=>{const {v}=await fixture(),a=await account(),other=await account(),{order,key,preview}=await placed(a,{variantId:v.id,quantity:2});expect((await db.productVariant.findUniqueOrThrow({where:{id:v.id}})).quantity).toBe(5);const replay=await a.client.call('/orders','POST',{previewToken:preview.previewToken,idempotencyKey:key,currency:'USD',fulfillment:{method:'pickup',address:'',notes:''}});expect(replay.json().id).toBe(order.id);expect((await other.client.call('/orders/'+order.id)).statusCode).toBe(404);expect((await a.client.call('/orders/'+order.id+'/cancel','POST',{})).statusCode).toBe(200);expect((await db.productVariant.findUniqueOrThrow({where:{id:v.id}})).quantity).toBe(5);});
it('requires approval again when price or FX changes, and validates delivery address',async()=>{const {v}=await fixture(),a=await account();await a.client.call('/cart','POST',{items:[{variantId:v.id,quantity:1}]});const preview=(await a.client.call('/cart')).json();await db.productVariant.update({where:{id:v.id},data:{priceUsd:'101'}});const payload={previewToken:preview.previewToken,idempotencyKey:randomUUID(),currency:'USD',fulfillment:{method:'pickup',address:'',notes:''}};expect((await a.client.call('/orders','POST',payload)).json().error.code).toBe('prices_changed');expect((await a.client.call('/orders','POST',{...payload,fulfillment:{method:'delivery',address:''}})).statusCode).toBe(400);});
it('allows only one concurrent completion of the last quantity and repeat completion deducts once',async()=>{const {v}=await fixture('quantity',1),a=await account(),b=await account(),admin=await staff(),first=await placed(a,{variantId:v.id,quantity:1}),second=await placed(b,{variantId:v.id,quantity:1});const one=await ready(admin,first.order),two=await ready(admin,second.order);const results=await Promise.all([admin.call('/commerce/orders/'+one.id+'/status','POST',{status:'completed',revision:one.updatedAt}),admin.call('/commerce/orders/'+two.id+'/status','POST',{status:'completed',revision:two.updatedAt})]);expect(results.map(r=>r.statusCode).sort()).toEqual([200,409]);expect((await db.productVariant.findUniqueOrThrow({where:{id:v.id}})).quantity).toBe(0);const winner=results.find(r=>r.statusCode===200)!.json();expect((await admin.call('/commerce/orders/'+winner.id+'/status','POST',{status:'completed',revision:winner.updatedAt})).statusCode).toBe(200);expect(await db.inventoryMovement.count({where:{variantId:v.id}})).toBe(1);expect((await admin.call('/commerce/orders/'+winner.id+'/status','POST',{status:'cancelled',revision:winner.updatedAt})).statusCode).toBe(409);},20000);
it('does not expose serial numbers, limits unit quantity, and cannot sell one unit twice',async()=>{const {v,unit,cat}=await fixture('serialized',0),a=await account(),b=await account(),admin=await staff();const r=await browser().call('/catalog?category='+cat);expect(JSON.stringify(r.json())).not.toContain(unit!.serialNumber);expect((await a.client.call('/cart','POST',{items:[{variantId:v.id,unitId:unit!.id,quantity:2}]})).statusCode).toBe(400);const one=await ready(admin,(await placed(a,{variantId:v.id,unitId:unit!.id,quantity:1})).order),two=await ready(admin,(await placed(b,{variantId:v.id,unitId:unit!.id,quantity:1})).order);const results=await Promise.all([admin.call('/commerce/orders/'+one.id+'/status','POST',{status:'completed',revision:one.updatedAt}),admin.call('/commerce/orders/'+two.id+'/status','POST',{status:'completed',revision:two.updatedAt})]);expect(results.map(r=>r.statusCode).sort()).toEqual([200,409]);expect((await db.inventoryUnit.findUniqueOrThrow({where:{id:unit!.id}})).available).toBe(false);},20000);
it('derives bundle availability from all components and aggregates stock across cart lines',async()=>{const {v}=await fixture('quantity',3),id=randomUUID();await db.catalogPackage.create({data:{id,slug:id,title:{ar:'باقة اختبار',en:'Test bundle'},description:{},priceMode:'fixed',priceUsd:'50',published:true,items:{create:{variantId:v.id,quantity:2}}}});const p=await cartPreview(db,[{packageId:id,quantity:1}]);expect(p.subtotalUsd).toBe('50.00');expect((p.items as SnapshotItem[])[0].quantity).toBe(2);await expect(cartPreview(db,[{packageId:id,quantity:1},{variantId:v.id,quantity:2}])).rejects.toThrow('insufficient_stock');});
it('enforces inventory, order and customer permissions and catches stale adjustments',async()=>{const {v}=await fixture(),editor=await staff('editor'),sales=await staff('sales'),owner=await staff();expect(can('sales','orders.manage')).toBe(true);expect((await editor.call('/commerce/inventory')).statusCode).toBe(403);expect((await editor.call('/commerce/orders')).statusCode).toBe(403);expect((await sales.call('/commerce/customers')).statusCode).toBe(403);expect((await owner.call('/commerce/inventory/adjust','POST',{variantId:v.id,delta:-99,reason:'Test invalid adjustment',revision:v.updatedAt.toISOString()})).json().error.code).toBe('negative_stock');expect((await owner.call('/commerce/inventory/adjust','POST',{variantId:v.id,delta:1,reason:'Test receipt',revision:'stale'})).statusCode).toBe(409);});
it('previews invalid import rows without mutation; successful import stays draft',async()=>{const {v,p}=await fixture(),admin=await staff(),rows=[{productId:p.id,sku:v.sku,priceUsd:'120',quantity:4,options:{ramGB:8},specs:{}}];const before=await db.productVariant.findUniqueOrThrow({where:{id:v.id}});const preview=await admin.call('/commerce/import','POST',{rows,commit:false});expect(preview.json().errors).toEqual([]);expect((await db.productVariant.findUniqueOrThrow({where:{id:v.id}})).priceUsd?.toString()).toBe(before.priceUsd?.toString());expect((await admin.call('/commerce/import','POST',{rows,commit:true,previewToken:preview.json().previewToken})).json().committed).toBe(true);expect((await db.product.findUniqueOrThrow({where:{id:p.id}})).status).toBe('draft');});
it('issues one-use expiring manual recovery links, revokes sessions and audits verification',async()=>{const a=await account(),admin=await staff(),r=await admin.call('/commerce/customers/'+a.c.id+'/recovery','POST',{verificationNote:'Verified in person with original purchase and identity'});expect(r.statusCode).toBe(200);const body={token:r.json().token,password:randomToken()},b=browser();await b.call('/csrf');expect((await b.call('/reset','POST',body)).statusCode).toBe(200);expect((await b.call('/reset','POST',body)).statusCode).toBe(400);expect((await a.client.call('/account')).json().customer).toBeNull();const audit=await db.auditLog.findFirstOrThrow({where:{entityId:a.c.id,action:'customer.recovery_issued'}});expect(JSON.stringify(audit)).not.toContain(body.token);},20000);
it('uses product template overrides and SKU display values rather than inherited display values',async()=>{
  const {p,v,cat}=await fixture(),typeId=randomUUID();
  await db.productType.create({data:{id:typeId,title:{ar:'شاشة',en:'Display'},fields:[{key:'refreshHz',title:{ar:'التردد',en:'Refresh rate'},valueType:'number',filterable:true,card:true,options:[],required:false,sort:0,unit:'Hz'}]}});
  await db.product.update({where:{id:p.id},data:{productTypeId:typeId,specs:{display:{hz:60,sizeIn:14}}}});
  await db.productVariant.update({where:{id:v.id},data:{specs:{refreshHz:144}}});
  const result=(await browser().call('/catalog?category='+cat+'&spec_refreshHz=144')).json();
  expect(result.total).toBe(1);expect(result.facets.specs.map((f:{key:string})=>f.key)).toEqual(['refreshHz']);expect(result.items[0].offers[0].specs.refreshHz).toBe(144);
});
it('checks automatic collection rules against the same unit and never exposes its serial in bundles',async()=>{
  const {p,v,unit,cat,brand}=await fixture('serialized',0),second=await db.inventoryUnit.create({data:{variantId:v.id,serialNumber:randomUUID(),condition:'A',batteryHealthPct:60,inspection:{},defects:[],images:[]}}),id=randomUUID();
  await db.catalogCollection.create({data:{id,slug:id,title:{ar:'مجموعة',en:'Collection'},description:{},mode:'automatic',published:true,rules:{categories:[cat],brands:[brand.id],conditions:['A'],available:true,min:null,max:null}}});
  let result=(await browser().call('/catalog?category='+cat+'&collection='+id+'&spec_batteryHealthPct=85')).json();expect(result.total).toBe(0);
  result=(await browser().call('/catalog?category='+cat+'&collection='+id)).json();expect(result.items[0].product.id).toBe(p.id);expect(result.items[0].offers.map((o:{unitId:string})=>o.unitId)).toEqual([second.id]);
  const packageId=randomUUID();await db.catalogPackage.create({data:{id:packageId,slug:packageId,title:{ar:'باقة',en:'Bundle'},description:{},priceMode:'sum',published:true,items:{create:{variantId:v.id,quantity:1}}}});
  const packages=(await browser().call('/packages')).json();expect(JSON.stringify(packages)).not.toContain(unit!.serialNumber);expect(JSON.stringify(packages)).not.toContain(second.serialNumber);
});
it('previews new product and unit imports, rejects stale previews, and keeps imported parents draft',async()=>{
  const {cat,brand}=await fixture(),admin=await staff(),id=randomUUID(),rows=[{productId:id,sku:'new-'+id,priceUsd:null,quantity:0,inventoryMode:'serialized',titleAr:'منتج اختبار الاستيراد',titleEn:'Import test product',category:cat,brandId:brand.id,options:{ramGB:8},specs:{}}];
  const preview=(await admin.call('/commerce/import','POST',{rows})).json();expect(preview.errors).toEqual([]);expect(await db.product.findUnique({where:{id}})).toBeNull();
  expect((await admin.call('/commerce/import','POST',{rows,commit:true,previewToken:preview.previewToken})).json().committed).toBe(true);
  const v=await db.productVariant.findUniqueOrThrow({where:{sku:rows[0].sku}});expect((await db.product.findUniqueOrThrow({where:{id}})).status).toBe('draft');
  const units=[{id:randomUUID(),variantId:v.id,serialNumber:randomUUID(),condition:'B',batteryHealthPct:'90',inspection:{passed:true},defects:[{ar:'خدش موضح',en:'Disclosed scratch'}],images:[]}];
  const unitPreview=(await admin.call('/commerce/import','POST',{kind:'units',rows:units})).json();expect(unitPreview.errors).toEqual([]);
  await db.productVariant.update({where:{id:v.id},data:{warrantyMonths:1}});
  expect((await admin.call('/commerce/import','POST',{kind:'units',rows:units,commit:true,previewToken:unitPreview.previewToken})).statusCode).toBe(409);
  const refreshed=(await admin.call('/commerce/import','POST',{kind:'units',rows:units})).json();
  expect((await admin.call('/commerce/import','POST',{kind:'units',rows:units,commit:true,previewToken:refreshed.previewToken})).json().committed).toBe(true);
  expect((await db.inventoryUnit.findUniqueOrThrow({where:{id:units[0].id}})).batteryHealthPct).toBe(90);expect(await db.inventoryMovement.count({where:{unitId:units[0].id}})).toBe(1);
});
it('records unit withdrawal with a reason, protects image references, and rejects equivalent option combinations',async()=>{
  const {v,unit,p}=await fixture('serialized',0),admin=await staff(),editor=await staff('editor'),reason='Withdraw for inspection';
  expect((await editor.call('/commerce/units/'+unit!.id+'/availability','POST',{available:false,revision:unit!.updatedAt.toISOString(),reason})).statusCode).toBe(403);
  expect((await admin.call('/commerce/units/'+unit!.id+'/availability','POST',{available:false,revision:unit!.updatedAt.toISOString(),reason})).statusCode).toBe(200);
  expect(await db.inventoryMovement.count({where:{unitId:unit!.id,reason,delta:-1}})).toBe(1);
  await db.product.update({where:{id:p.id},data:{status:'draft'}});
  const variant={id:v.id,productId:p.id,sku:v.sku,priceUsd:'100.00',inventoryMode:'serialized',condition:'A',active:true,images:[],warrantyMonths:null,specs:{ramGB:8},options:{ports:['usb','hdmi']},revision:(await db.productVariant.findUniqueOrThrow({where:{id:v.id}})).updatedAt.toISOString()};
  expect((await admin.call('/commerce/variants','POST',variant)).statusCode).toBe(200);
  expect((await admin.call('/commerce/variants','POST',{...variant,id:randomUUID(),sku:'other-'+randomUUID(),options:{ports:['hdmi','usb']},revision:undefined})).statusCode).toBe(409);
  const media=await db.mediaAsset.create({data:{id:randomUUID(),kind:'image',originalPath:'/api/media/'+randomUUID(),variants:{},mime:'image/webp',bytes:1,altAr:'اختبار',altEn:'Test'}});
  await db.productVariant.update({where:{id:v.id},data:{images:[media.originalPath]}});
  expect((await admin.call('/media/'+media.id,'DELETE')).json().error.code).toBe('image_in_use');
});






